/**
 * Ett verkligt svar från SMHI:s SNOW-API, kapat till fjorton tidssteg.
 *
 * Fixturen är hämtad 2026-08-25 för punkten Stockholm
 * (lon 18.0686, lat 59.3293). Poängen med att spara ett äkta svar är att
 * tolkningen ska brytas i ett test om SMHI ändrar formatet — vilket de gjorde
 * 31 mars 2026 när pmp3g ersattes av snow1g.
 */
export const SMHI_RESPONSE = {
  "timeSeries": [
    {
      "time": "2026-08-25T10:00:00Z",
      "intervalParametersStartTime": "2026-08-25T09:00:00Z",
      "data": {
        "air_temperature": 20.5,
        "wind_from_direction": 4,
        "wind_speed": 2.7,
        "wind_speed_of_gust": 6.7,
        "relative_humidity": 50,
        "air_pressure_at_mean_sea_level": 1022.1,
        "visibility_in_air": 38.5,
        "thunderstorm_probability": 1,
        "probability_of_frozen_precipitation": 0,
        "cloud_area_fraction": 4,
        "low_type_cloud_area_fraction": 4,
        "medium_type_cloud_area_fraction": 0,
        "high_type_cloud_area_fraction": 0,
        "cloud_base_altitude": 9999,
        "cloud_top_altitude": 9999,
        "precipitation_amount_mean_deterministic": 0,
        "precipitation_amount_mean": 0,
        "precipitation_amount_min": 0,
        "precipitation_amount_max": 0,
        "precipitation_amount_median": 0,
        "probability_of_precipitation": 0,
        "precipitation_frozen_part": -9,
        "predominant_precipitation_type_at_surface": 0,
        "symbol_code": 3
      }
    },
    {
      "time": "2026-08-25T11:00:00Z",
      "intervalParametersStartTime": "2026-08-25T10:00:00Z",
      "data": {
        "air_temperature": 20.5,
        "wind_from_direction": 3,
        "wind_speed": 2.7,
        "wind_speed_of_gust": 6.7,
        "relative_humidity": 51,
        "air_pressure_at_mean_sea_level": 1022.5,
        "visibility_in_air": 37.8,
        "thunderstorm_probability": 3,
        "probability_of_frozen_precipitation": 0,
        "cloud_area_fraction": 5,
        "low_type_cloud_area_fraction": 8,
        "medium_type_cloud_area_fraction": 8,
        "high_type_cloud_area_fraction": 0,
        "cloud_base_altitude": 1504,
        "cloud_top_altitude": 1961,
        "precipitation_amount_mean_deterministic": 0,
        "precipitation_amount_mean": 0,
        "precipitation_amount_min": 0,
        "precipitation_amount_max": 0,
        "precipitation_amount_median": 0,
        "probability_of_precipitation": 0,
        "precipitation_frozen_part": -9,
        "predominant_precipitation_type_at_surface": 0,
        "symbol_code": 3
      }
    },
    {
      "time": "2026-08-25T12:00:00Z",
      "intervalParametersStartTime": "2026-08-25T11:00:00Z",
      "data": {
        "air_temperature": 20.3,
        "wind_from_direction": 18,
        "wind_speed": 2.6,
        "wind_speed_of_gust": 6.1,
        "relative_humidity": 54,
        "air_pressure_at_mean_sea_level": 1022.9,
        "visibility_in_air": 35.9,
        "thunderstorm_probability": 5,
        "probability_of_frozen_precipitation": 0,
        "cloud_area_fraction": 6,
        "low_type_cloud_area_fraction": 8,
        "medium_type_cloud_area_fraction": 8,
        "high_type_cloud_area_fraction": 0,
        "cloud_base_altitude": 1646,
        "cloud_top_altitude": 2136,
        "precipitation_amount_mean_deterministic": 0,
        "precipitation_amount_mean": 0,
        "precipitation_amount_min": 0.1,
        "precipitation_amount_max": 0.1,
        "precipitation_amount_median": 0,
        "probability_of_precipitation": 3,
        "precipitation_frozen_part": 0,
        "predominant_precipitation_type_at_surface": 1,
        "symbol_code": 4
      }
    },
    {
      "time": "2026-08-25T13:00:00Z",
      "intervalParametersStartTime": "2026-08-25T12:00:00Z",
      "data": {
        "air_temperature": 20.5,
        "wind_from_direction": 26,
        "wind_speed": 2.4,
        "wind_speed_of_gust": 5.6,
        "relative_humidity": 53,
        "air_pressure_at_mean_sea_level": 1022.9,
        "visibility_in_air": 36.2,
        "thunderstorm_probability": 3,
        "probability_of_frozen_precipitation": 0,
        "cloud_area_fraction": 8,
        "low_type_cloud_area_fraction": 8,
        "medium_type_cloud_area_fraction": 8,
        "high_type_cloud_area_fraction": 0,
        "cloud_base_altitude": 1799,
        "cloud_top_altitude": 1962,
        "precipitation_amount_mean_deterministic": 0,
        "precipitation_amount_mean": 0,
        "precipitation_amount_min": 0.2,
        "precipitation_amount_max": 0.2,
        "precipitation_amount_median": 0,
        "probability_of_precipitation": 7,
        "precipitation_frozen_part": 0,
        "predominant_precipitation_type_at_surface": 1,
        "symbol_code": 4
      }
    },
    {
      "time": "2026-08-25T14:00:00Z",
      "intervalParametersStartTime": "2026-08-25T13:00:00Z",
      "data": {
        "air_temperature": 20.5,
        "wind_from_direction": 79,
        "wind_speed": 1.6,
        "wind_speed_of_gust": 5.5,
        "relative_humidity": 53,
        "air_pressure_at_mean_sea_level": 1023,
        "visibility_in_air": 36.3,
        "thunderstorm_probability": 3,
        "probability_of_frozen_precipitation": 0,
        "cloud_area_fraction": 7,
        "low_type_cloud_area_fraction": 6,
        "medium_type_cloud_area_fraction": 4,
        "high_type_cloud_area_fraction": 0,
        "cloud_base_altitude": 9999,
        "cloud_top_altitude": 9999,
        "precipitation_amount_mean_deterministic": 0,
        "precipitation_amount_mean": 0,
        "precipitation_amount_min": 0,
        "precipitation_amount_max": 0,
        "precipitation_amount_median": 0,
        "probability_of_precipitation": 0,
        "precipitation_frozen_part": -9,
        "predominant_precipitation_type_at_surface": 0,
        "symbol_code": 4
      }
    },
    {
      "time": "2026-08-25T15:00:00Z",
      "intervalParametersStartTime": "2026-08-25T14:00:00Z",
      "data": {
        "air_temperature": 20.4,
        "wind_from_direction": 90,
        "wind_speed": 1.1,
        "wind_speed_of_gust": 4.3,
        "relative_humidity": 53,
        "air_pressure_at_mean_sea_level": 1023.3,
        "visibility_in_air": 36.1,
        "thunderstorm_probability": 3,
        "probability_of_frozen_precipitation": 0,
        "cloud_area_fraction": 8,
        "low_type_cloud_area_fraction": 7,
        "medium_type_cloud_area_fraction": 5,
        "high_type_cloud_area_fraction": 0,
        "cloud_base_altitude": 1964,
        "cloud_top_altitude": 1963,
        "precipitation_amount_mean_deterministic": 0,
        "precipitation_amount_mean": 0,
        "precipitation_amount_min": 0,
        "precipitation_amount_max": 0,
        "precipitation_amount_median": 0,
        "probability_of_precipitation": 0,
        "precipitation_frozen_part": -9,
        "predominant_precipitation_type_at_surface": 0,
        "symbol_code": 6
      }
    },
    {
      "time": "2026-08-25T16:00:00Z",
      "intervalParametersStartTime": "2026-08-25T15:00:00Z",
      "data": {
        "air_temperature": 20.1,
        "wind_from_direction": 62,
        "wind_speed": 1.2,
        "wind_speed_of_gust": 3.4,
        "relative_humidity": 54,
        "air_pressure_at_mean_sea_level": 1023.4,
        "visibility_in_air": 35.9,
        "thunderstorm_probability": 2,
        "probability_of_frozen_precipitation": 0,
        "cloud_area_fraction": 4,
        "low_type_cloud_area_fraction": 3,
        "medium_type_cloud_area_fraction": 1,
        "high_type_cloud_area_fraction": 0,
        "cloud_base_altitude": 9999,
        "cloud_top_altitude": 9999,
        "precipitation_amount_mean_deterministic": 0,
        "precipitation_amount_mean": 0,
        "precipitation_amount_min": 0,
        "precipitation_amount_max": 0,
        "precipitation_amount_median": 0,
        "probability_of_precipitation": 0,
        "precipitation_frozen_part": -9,
        "predominant_precipitation_type_at_surface": 0,
        "symbol_code": 3
      }
    },
    {
      "time": "2026-08-25T17:00:00Z",
      "intervalParametersStartTime": "2026-08-25T16:00:00Z",
      "data": {
        "air_temperature": 19.4,
        "wind_from_direction": 41,
        "wind_speed": 1.5,
        "wind_speed_of_gust": 3.6,
        "relative_humidity": 54,
        "air_pressure_at_mean_sea_level": 1023.4,
        "visibility_in_air": 35.6,
        "thunderstorm_probability": 1,
        "probability_of_frozen_precipitation": 0,
        "cloud_area_fraction": 2,
        "low_type_cloud_area_fraction": 1,
        "medium_type_cloud_area_fraction": 0,
        "high_type_cloud_area_fraction": 1,
        "cloud_base_altitude": 9999,
        "cloud_top_altitude": 9999,
        "precipitation_amount_mean_deterministic": 0,
        "precipitation_amount_mean": 0,
        "precipitation_amount_min": 0.2,
        "precipitation_amount_max": 0.2,
        "precipitation_amount_median": 0,
        "probability_of_precipitation": 3,
        "precipitation_frozen_part": 0,
        "predominant_precipitation_type_at_surface": 1,
        "symbol_code": 2
      }
    },
    {
      "time": "2026-08-25T18:00:00Z",
      "intervalParametersStartTime": "2026-08-25T17:00:00Z",
      "data": {
        "air_temperature": 18.3,
        "wind_from_direction": 29,
        "wind_speed": 0.8,
        "wind_speed_of_gust": 3.1,
        "relative_humidity": 56,
        "air_pressure_at_mean_sea_level": 1023.7,
        "visibility_in_air": 34.5,
        "thunderstorm_probability": 1,
        "probability_of_frozen_precipitation": 0,
        "cloud_area_fraction": 5,
        "low_type_cloud_area_fraction": 1,
        "medium_type_cloud_area_fraction": 0,
        "high_type_cloud_area_fraction": 5,
        "cloud_base_altitude": 9999,
        "cloud_top_altitude": 9999,
        "precipitation_amount_mean_deterministic": 0,
        "precipitation_amount_mean": 0,
        "precipitation_amount_min": 0,
        "precipitation_amount_max": 0,
        "precipitation_amount_median": 0,
        "probability_of_precipitation": 0,
        "precipitation_frozen_part": -9,
        "predominant_precipitation_type_at_surface": 0,
        "symbol_code": 3
      }
    },
    {
      "time": "2026-08-25T19:00:00Z",
      "intervalParametersStartTime": "2026-08-25T18:00:00Z",
      "data": {
        "air_temperature": 17.1,
        "wind_from_direction": 101,
        "wind_speed": 1.3,
        "wind_speed_of_gust": 1.7,
        "relative_humidity": 65,
        "air_pressure_at_mean_sea_level": 1024.1,
        "visibility_in_air": 28,
        "thunderstorm_probability": 1,
        "probability_of_frozen_precipitation": 0,
        "cloud_area_fraction": 3,
        "low_type_cloud_area_fraction": 0,
        "medium_type_cloud_area_fraction": 0,
        "high_type_cloud_area_fraction": 3,
        "cloud_base_altitude": 9999,
        "cloud_top_altitude": 9999,
        "precipitation_amount_mean_deterministic": 0,
        "precipitation_amount_mean": 0,
        "precipitation_amount_min": 0,
        "precipitation_amount_max": 0,
        "precipitation_amount_median": 0,
        "probability_of_precipitation": 0,
        "precipitation_frozen_part": -9,
        "predominant_precipitation_type_at_surface": 0,
        "symbol_code": 2
      }
    },
    {
      "time": "2026-08-25T20:00:00Z",
      "intervalParametersStartTime": "2026-08-25T19:00:00Z",
      "data": {
        "air_temperature": 16.4,
        "wind_from_direction": 186,
        "wind_speed": 1.9,
        "wind_speed_of_gust": 2.9,
        "relative_humidity": 69,
        "air_pressure_at_mean_sea_level": 1024.4,
        "visibility_in_air": 25.6,
        "thunderstorm_probability": 1,
        "probability_of_frozen_precipitation": 0,
        "cloud_area_fraction": 2,
        "low_type_cloud_area_fraction": 0,
        "medium_type_cloud_area_fraction": 0,
        "high_type_cloud_area_fraction": 2,
        "cloud_base_altitude": 9999,
        "cloud_top_altitude": 9999,
        "precipitation_amount_mean_deterministic": 0,
        "precipitation_amount_mean": 0,
        "precipitation_amount_min": 0,
        "precipitation_amount_max": 0,
        "precipitation_amount_median": 0,
        "probability_of_precipitation": 0,
        "precipitation_frozen_part": -9,
        "predominant_precipitation_type_at_surface": 0,
        "symbol_code": 2
      }
    },
    {
      "time": "2026-08-25T21:00:00Z",
      "intervalParametersStartTime": "2026-08-25T20:00:00Z",
      "data": {
        "air_temperature": 15.7,
        "wind_from_direction": 198,
        "wind_speed": 1.6,
        "wind_speed_of_gust": 2.6,
        "relative_humidity": 72,
        "air_pressure_at_mean_sea_level": 1024.6,
        "visibility_in_air": 23.3,
        "thunderstorm_probability": 1,
        "probability_of_frozen_precipitation": 0,
        "cloud_area_fraction": 3,
        "low_type_cloud_area_fraction": 0,
        "medium_type_cloud_area_fraction": 0,
        "high_type_cloud_area_fraction": 3,
        "cloud_base_altitude": 9999,
        "cloud_top_altitude": 9999,
        "precipitation_amount_mean_deterministic": 0,
        "precipitation_amount_mean": 0,
        "precipitation_amount_min": 0,
        "precipitation_amount_max": 0,
        "precipitation_amount_median": 0,
        "probability_of_precipitation": 0,
        "precipitation_frozen_part": -9,
        "predominant_precipitation_type_at_surface": 0,
        "symbol_code": 2
      }
    },
    {
      "time": "2026-08-25T22:00:00Z",
      "intervalParametersStartTime": "2026-08-25T21:00:00Z",
      "data": {
        "air_temperature": 15.4,
        "wind_from_direction": 209,
        "wind_speed": 1.1,
        "wind_speed_of_gust": 2.2,
        "relative_humidity": 76,
        "air_pressure_at_mean_sea_level": 1025.1,
        "visibility_in_air": 21.1,
        "thunderstorm_probability": 1,
        "probability_of_frozen_precipitation": 0,
        "cloud_area_fraction": 0,
        "low_type_cloud_area_fraction": 0,
        "medium_type_cloud_area_fraction": 0,
        "high_type_cloud_area_fraction": 0,
        "cloud_base_altitude": 9999,
        "cloud_top_altitude": 9999,
        "precipitation_amount_mean_deterministic": 0,
        "precipitation_amount_mean": 0,
        "precipitation_amount_min": 0,
        "precipitation_amount_max": 0,
        "precipitation_amount_median": 0,
        "probability_of_precipitation": 0,
        "precipitation_frozen_part": -9,
        "predominant_precipitation_type_at_surface": 0,
        "symbol_code": 1
      }
    },
    {
      "time": "2026-08-25T23:00:00Z",
      "intervalParametersStartTime": "2026-08-25T22:00:00Z",
      "data": {
        "air_temperature": 15,
        "wind_from_direction": 226,
        "wind_speed": 1.1,
        "wind_speed_of_gust": 1.6,
        "relative_humidity": 78,
        "air_pressure_at_mean_sea_level": 1025.5,
        "visibility_in_air": 19.8,
        "thunderstorm_probability": 1,
        "probability_of_frozen_precipitation": 0,
        "cloud_area_fraction": 0,
        "low_type_cloud_area_fraction": 0,
        "medium_type_cloud_area_fraction": 0,
        "high_type_cloud_area_fraction": 0,
        "cloud_base_altitude": 9999,
        "cloud_top_altitude": 9999,
        "precipitation_amount_mean_deterministic": 0,
        "precipitation_amount_mean": 0,
        "precipitation_amount_min": 0,
        "precipitation_amount_max": 0,
        "precipitation_amount_median": 0,
        "probability_of_precipitation": 0,
        "precipitation_frozen_part": -9,
        "predominant_precipitation_type_at_surface": 0,
        "symbol_code": 1
      }
    }
  ]
} as const;
